version: "3"

services:
  temp_sensor:
    image: primaklubov/sim_sensor
    environment:
      - SIM_HOST=192.168.1.1
      - SIM_NAME=sim_1
      - SIM_PERIOD=5
      - SIM_TYPE=temperature
  pressure_sensor:
    image: primaklubov/sim_sensor
    environment:
      - SIM_HOST=192.168.1.1
      - SIM_NAME=sim_2
      - SIM_PERIOD=5
      - SIM_TYPE=pressure
  current_sensor:
    image: primaklubov/sim_sensor
    environment:
      - SIM_HOST=192.168.1.1
      - SIM_NAME=sim_3
      - SIM_PERIOD=1
      - SIM_TYPE=current
  humidity_sensor:
    image: primaklubov/sim_sensor
    environment:
      - SIM_HOST=192.168.1.1
      - SIM_NAME=sim_4
      - SIM_PERIOD=10
      - SIM_TYPE=humidity                                         